kind: pipeline
name: production

steps:
  - name: deploy
    image: alpine
    commands:
    - echo deploy
  - name: notify
    image: alpine
    commands:
    - echo notify

trigger:
  branch:
  - master
  event:
  - tag

---

kind: pipeline
name: staging

steps:
  - name: build
    image: alpine
    commands:
    - echo build some code

  - name: test
    image: alpine
    commands:
    - echo run test12

trigger:
  branch:
  - master
  event:
  - push