kind: pipeline
name: production

when:
  branch:
  - master
  event:
  - tag

steps:
- name: deploy
  image: alpine
  commands:
  - echo deploy

---

kind: pipeline
name: default

steps:
  - name: build
    image: alpine
    commands:
    - echo build some code

  - name: test
    image: alpine
    commands:
    - echo run test12