kind: pipeline
name: production

steps:
- name: deploy
  image: alpine
  commands:
  - echo deploy

trigger:
  branch:
  - master
  event:
  - tag

---

kind: pipeline
name: dev

steps:
  - name: build
    image: alpine
    commands:
    - echo build some code

  - name: test
    image: alpine
    commands:
    - echo run test12

trigger:
  branch:
  - dev