- name: "install docker"
  hosts: all
  become: true
  pre_tasks:
    - name: Add universe repository for bionic
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'
  post_tasks:
    - name: 'install pip'
      apt:
        name: python-pip
        update_cache: yes
    - name: 'install docker-py'
      pip:
        name: docker
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
  roles:
    - role: "nickjj.docker"