Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.network "private_network", ip: "192.168.1.2"
    server.vm.network "forwarded_port", guest: 80, host: 80
    server.vm.network "forwarded_port", guest: 443, host: 443
  end

  config.vm.define "agent" do |agent|
    agent.vm.box = "ubuntu/bionic64"
    agent.vm.network "private_network", ip: "192.168.1.3"
    agent.vm.network "forwarded_port", guest: 3000, host: 3000
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yaml"
  end

  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false

end
